server:
    port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: root
    hikari:
      data-source-properties:
        useSSL: false
        serverTimezone: GMT+8
        useUnicode: true
        characterEncoding: utf8
        # 这个必须要加，否则 Activiti 自动建表会失败
        nullCatalogMeansCurrent: true
#logging:
#    level:
#        net.javacrumbs.shedlock: DEBUG
